# Generated by Django 5.1.2 on 2024-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cryptocurrency", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("market_cap", models.CharField(max_length=100)),
                ("change", models.CharField(max_length=100)),
            ],
        ),
    ]
